### ISSUE TITLE
autoComplete one-time-code not working on iOS Chrome

### ISSUE THREAD

**Issue by hakanozkaptan** [ritikbanger/react18-input-otp#1]
on iOS chrome when you click on the OTP that pops up above the keyboard it only pastes the 1st digit in the otp box.

**Comment by ritikbanger** [comment]
Hello @hakanozkaptan, could you provide with a video example of the same. As we have handled this case for iOS, we need to look at it again.

Also, please mention the device you are facing this issue on.

**Comment by ritikbanger** [comment]
@hakanozkaptan I would be fixing this in this build too. Also, PRs are welcome.

**Comment by hakanozkaptan** [comment]
I have tried, please ignore mine, but maxLength 1 is causing a problem, I need to fix it

**Comment by hakanozkaptan** [comment]
pr opened @ritikbanger
