### ISSUE TITLE
The value is updated at the wrong index

### ISSUE THREAD

**Issue by goonerDp** [ritikbanger/react18-input-otp#10]
**Steps to reproduce the issue**:
- Enter some code (123456) for example at https://codesandbox.io/s/react18-input-otp-0nxzx7?file=/src/App.js
- Try to update any field

**Actual result**:
The wrong field is updated

**Comment by ritikbanger** [comment]
I will have a look and fix this. Thanks for reporting.

**Comment by ritikbanger** [comment]
@goonerDp This is fixed.
