### ISSUE TITLE
Update peerDependencies to support React 16 and 17

### ISSUE THREAD

**Issue by goonerDp** [ritikbanger/react18-input-otp#11]
Could you change the peerDependencies to get rid of warnings on React 16, and 17?

**Comment by ritikbanger** [comment]
The package name is 'react18-input-otp', that itself indicates that the project is mainly build for React v18, though we would add >=16 in the upcoming update to avoid this warning.

**Comment by ritikbanger** [comment]
This is fixed in the new update!
