### ISSUE TITLE
Can we please have support for react 17?

### ISSUE THREAD

**Issue by DanishOnGit** [ritikbanger/react18-input-otp#13]
- **Describe the Feature Request**

Please provide support for React 17 also.
```
Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.1.0" from react18-input-otp@1.1.0
npm ERR! node_modules/react18-input-otp
npm ERR!   react18-input-otp@"*" from the root project
```

Btw, Thanks a lot Ritik! This component helped me in one of my react 18 projects!
- **Describe Preferred Solution**

**Comment by ritikbanger** [comment]
npm i --legacy-peer-deps

**Comment by ritikbanger** [comment]
You can resolve it manually in the package.json with the [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) rule for npm (>=8) or with resolutions for yarn:

NPM example:

```
"overrides": {
    "react-otp-input": {
      "react": "$react",
      "react-dom": "$react-dom"
    }
 }
```

**Comment by ritikbanger** [comment]
New version resolve this issue. Thanks.
