### ISSUE TITLE
Success Status

### ISSUE THREAD

**Issue by sucodev** [ritikbanger/react18-input-otp#17]
Please implement a way to show a success status, just like you have for error.

**Comment by ritikbanger** [comment]
Hello @sucodev, Can you show more information on how you wish to have this new feature?

A quick approach can be to have a `isSuccess` prop that will turn the input boxes to green color showing success. Let me know your thoughts.

**Comment by ritikbanger** [comment]
#18

**Comment by ritikbanger** [comment]
We have added the support for success in v1.1.3. Please update to the latest for the feature you are expecting!

**Comment by sucodev** [comment]
Thanksssss

**Comment by ritikbanger** [comment]
Don't forget to star the repo and it would be of great help if you tweet about the package.
