### ISSUE TITLE
I want to hide copy/paste modal on mobile browsers

### ISSUE THREAD

**Issue by joshua-watersport** [ritikbanger/react18-input-otp#21]
when I clipboard paste the otp code, show the copy/paste modal like this.
![228993502-4a101beb-e746-432f-8b45-2c55196d00ee](https://user-images.githubusercontent.com/121116326/230254742-68594eca-653d-4ebd-80c6-3bcc5b7f1da1.png)
how can I fix?

**Comment by ritikbanger** [comment]
This is not an issue. You only need to blur the input. For further query refer to this discussion: https://github.com/ritikbanger/react18-input-otp/discussions/20#discussion-5028775
