### ISSUE TITLE
On Desktop/Browser (not Mobile), "tab" key on keyboard doesn't change focus

### ISSUE THREAD

**Issue by m00gl3** [ritikbanger/react18-input-otp#24]
Hi,
I'm also running this OtpInput on a desktop/laptop browser (not mobile), and as part of my accessibility testing I try to move between elements in the OTP via "tab" button on the keyboard.  It doesn't change focus to next element.

I have to manually enter a number in the first cell, and then it works - pressing tab changes the focus to the next element.

This happens with and without shouldAutoFocus

**Comment by ritikbanger** [comment]
This is a feature and we do not allow to write otp from in between indexes without filling the previous one. If we allow, it would result in unwanted bugs.

Once you fills the data, tab navigation would be enabled.

Let me know if you are missing any specific functionality with the current behavior and I would be happy to help.

**Comment by m00gl3** [comment]
Thanks you're right - it should be as you've made it
