### ISSUE TITLE
Editing the digit doesn't work properly in Focus state of an Input field

### ISSUE THREAD

**Issue by prachi09051999** [ritikbanger/react18-input-otp#34]
- **Describe the Feature Request**
When I enter the OTP and want to edit any digit, If I enter into the focus state by double-clicking the input field and try to edit that digit, it doesn't work. In the below sandbox example, it does nothing in the focus state but in some other use cases, it edits the next digit, and the focus also goes to any random place.
Link of the image with the referred focus state - https://drive.google.com/file/d/15wA4Cxq9HX8NrsVZ1MfeQAVSMt3WaREV/view?usp=sharing
[CodeSandbox Link](https://codesandbox.io/s/material-ui-forked-pqwfrv?file=/Test.js)
- **Describe Preferred Solution**

**Comment by ritikbanger** [comment]
Please share a screen recording/video demonstrating your issue. Also, update your codesandbox to use version 1.1.4

**Comment by prachi09051999** [comment]
[Issue Video](https://drive.google.com/file/d/1F6pAZRQaXYuO1-7b3DEKdIQAdyabUKK7/view?usp=sharing)
Sure, I've added the video of the error here. Let me walk you through the steps that lead to this issue:

1. Start by entering the One-Time Password (OTP) for all the fields.
2. Now, go to any input field and click on it to edit the digit. You'll see, just like in the video, you can change a digit, such as from '2' to '9.'
3. The problem arises when you try to double-click on an input field and reach to focus state to edit it further. It doesn't work. As shown in the video, trying multiple times to edit the number '3,' the field remains unfazed and doesn't let you make any changes.

In my opinion, the input field shouldn't show the focus state if it doesn't allow editing. Alternatively, it would be better if the system had a consistent behavior with 'one click and edit' in the focus state too for a smoother user experience.

Note: I'm not able to add version 1.0.4 in Sandbox but am using it in my personal project and have faced the same problem.

**Comment by ritikbanger** [comment]
Hi @prachi09051999 , there are a few things.

1: In your codesandbox, you are using `react18-otp-input` package while you should be using `react18-input-otp`
2: That's the reason, you are not able to update to version 1.1.4
3. Kindly update your codesandbox to use this package and the problem will be solved.

![image](https://github.com/ritikbanger/react18-input-otp/assets/47841501/317a3964-d553-499a-9efc-0ec2c61f4f13)

**Comment by ritikbanger** [comment]
Re-open this ticket if you still face the issue.

**Comment by prachi09051999** [comment]
Thank you very much for bringing this matter to my attention. It has greatly assisted me in identifying the actual problem. 

The issue is related to the focus state when editing one input field, as it inadvertently affects the next input field, and the focus behavior becomes erratic, leading to unexpected results. 
I am using the latest version available in Sandbox which is 1.1.3.

<img width="343" alt="Screenshot 2023-07-25 at 11 55 34 AM" src="https://github.com/ritikbanger/react18-input-otp/assets/34397111/94e705ca-5e35-405d-9e25-7e9258de8894">


[Sandbox Link](https://codesandbox.io/s/material-ui-forked-pqwfrv?file=/Test.js)

I would like to share a video illustrating the exact problem for further clarification. Your prompt attention to this matter is greatly appreciated.

https://github.com/ritikbanger/react18-input-otp/assets/34397111/d41bcec7-8a56-458c-abd7-67a3b6d278ea

Let me also add the steps to generate the issue -
1. Start by entering the One-Time Password (OTP) for all the fields.
2. Now, go to any input field and click on it to edit the digit. You'll see, just like in the video, you can change a digit, such as from '2' to '9.'
3. The actual problem arises when you try to double-click on an input field and reach to focus state to edit it further. It doesn't work. As shown in the video, trying to edit the number '3' to '8' leads to the alteration of the next digit '4' to '8', and the focus goes to the last field.

**Comment by ritikbanger** [comment]
The behaviour is expected. If your cursor selects the field then the field will be edited. While if your cursor has not selected the field then it will update the nearest input field. If your cursor is on right on the input text then right side field would be edited, if your cursor is on left then the focused field would be edited.

let me know your thoughts.

**Comment by prachi09051999** [comment]
The cursor behavior when editing an input field should align with user expectations. 
Currently, when the cursor is on the right of one field, but editing the next one, it confuses users. To improve, we can keep the cursor within the edited field only to enhance user experience and predictability.
