### ISSUE TITLE
Keyboard do not pop up with shouldAutoFocus to true in mobile browsers 

### ISSUE THREAD

**Issue by alizaib-1m** [ritikbanger/react18-input-otp#35]
- **Describe the Feature Request**
When **shouldAutoFocus** is set to true, the field in focused on initial render but when the app is opened in a mobile browser the keyboard do not pop up. We have to click the field to show keyboard

- **Describe Preferred Solution**

**Comment by ritikbanger** [comment]
Kindly mention the OS, browser, and other device information.

Should auto focus works fine on all android devices. On iOS, it is OS restrictions.

**Comment by alizaib-1m** [comment]
@ritikbanger I checked in both **safari iOS (16.0)** and **chrome browser on android**. Both had the same problem. 
The field is focused but the keyboard do not pop up unless pressed on the field again to start typing.

**Comment by ritikbanger** [comment]
It is working fine on Android. Please check the codesandbox: https://codesandbox.io/s/react18-input-otp-0nxzx7?file=/src/App.js

**Comment by alizaib-1m** [comment]
Yes it works on android devices

**Comment by ritikbanger** [comment]
Kindly refer to this comment here:

https://github.com/ritikbanger/react18-input-otp/discussions/31#discussioncomment-6405382
