### ISSUE TITLE
Placeholder styling

### ISSUE THREAD

**Issue by DashaKavalenka** [ritikbanger/react18-input-otp#36]
- **Describe the Feature Request**
There is no way to change the style of the placeholder in inputs.
- **Describe Preferred Solution**
I haven't found a solution to this problem yet.

**Comment by ritikbanger** [comment]
You can do this in your code also.

```
input::placeholder {
  font-weight: bold;
  opacity: 0.5;
  color: red;
}
```


Here is the output and css
![image](https://github.com/ritikbanger/react18-input-otp/assets/47841501/11617afb-09e4-4fca-b72a-89effb5acda1)

![image](https://github.com/ritikbanger/react18-input-otp/assets/47841501/062561a3-3a61-4454-873c-0d36c92563f1)


You can learn more from here:

https://www.w3schools.com/howto/howto_css_placeholder.asp#:~:text=In%20most%20browsers%2C%20the%20placeholder,opacity%3A%201%20to%20fix%20this.

OR if you don't want to apply style to all inputs then do this:

1. Pass unique Id to OTP input

```
<OtpInput
      id="myInput"
      placeholder="abcdef"
      value={otp}
      onChange={handleChange}
      numInputs={6}
      isSuccessed={false}
      errorStyle="error"
      successStyle="success"
      separator={<span>-</span>}
      separateAfter={3}
      shouldAutoFocus
      onSubmit={console.log(otp)}
    />
```


2. In your project styles add placeholder styles for this input id. You need to add array index to apply style i.e. `id-index`

```
 #myInput-0::placeholder {
  color: red;
}

#myInput-1::placeholder {
  color: green;
}

#myInput-2::placeholder {
  color: blue;
}
#myInput-3::placeholder {
  color: violet;
}

#myInput-4::placeholder {
  color: black;
}

#myInput-5::placeholder {
  color: brown;
}
```

Here is the output:

![image](https://github.com/ritikbanger/react18-input-otp/assets/47841501/1874e4d5-9cea-4210-aecc-0b11d9be8f00)

**Comment by DashaKavalenka** [comment]
Thnx!
I've seen this method, but how do this without css file ?

**Comment by ritikbanger** [comment]
You cannot pass inline css to pseudo elements.
