### ISSUE TITLE
Disable Default Styling

### ISSUE THREAD

**Issue by thedanmwangi** [ritikbanger/react18-input-otp#39]
- **Describe the Feature Request**
- Tailwind, Bootstrap and other CSS frameworks have done a great job in providing us templates for Inputs. But your package provides custom styling using the `style=""` attribute. This, in the 2 cases I have used, messes up Tailwind styling.
- I have also tried the `react-input-otp` package which this is built on top of, but the `skipDefaultStyles` doesn't work effectively. Upon rerendering, it converts back to adding the styles.

- **Describe Preferred Solution**
- By adding a proper and working `skipDefaultStyles` functionality, the package will enable users to disable this automatically.

**Comment by ritikbanger** [comment]
We do not have any style prop, try using `inputStyle` or `containerStyle`  prop as per your convenience, do you want us to pass a prop skipDefaultStyles and disable the style on container as well as on inputs?

**Comment by thedanmwangi** [comment]
Thanks for the quick reply.
True, you don/t have a style prop, but by default, in the HTML elements a style is passed to the container as well as the Inputs. (See attached).
I understand why this could be necessary to facilitate an easier onboarding to the package; but it most often affects the classNames passed to the Inputs.

And yes, I think skipDefaultStyles would be a great prop to have which disables the styles (see attached).

![Screenshot 2023-12-06 203157](https://github.com/ritikbanger/react18-input-otp/assets/66394054/36b9f1b6-f96d-4ff9-a0fa-5fcca291d0ab)

**Comment by ritikbanger** [comment]
I will provide you with a new patch version shortly by the upcoming weekend.

**Comment by ritikbanger** [comment]
On Further brainstorming, I think adding the prop `skipDefaultStyles` would be a bad idea due to few things:

1. It will led the developers to put unnecessary efforts.
2. Anytime you can override the default styles by using `!important`

Example.

```
.inputStyle {
  width: 3rem !important;
  height: 3rem;
  margin: 0 1rem;
  font-size: 2rem;
  border-radius: 4px;
  border: 1px solid rgba(0, 0, 0, 0.3);
}

<OtpInput
  id="otp-input"
  autoComplete="one-time-code"
  inputStyle="inputStyle"
  numInputs={numInputs}
  isDisabled={isDisabled}
  separateAfter={separateAfter}
  hasErrored={hasErrored}
  errorStyle="error"
  isSuccessed={isSuccessed}
  successStyle="success"
  onChange={this.handleOtpChange}
  separator={<span>{separator}</span>}
  isInputNum={isInputNum}
  isInputSecure={isInputSecure}
  shouldAutoFocus
  value={otp}
  placeholder={placeholder}
  onSubmit={() => console.log(otp)}
/>;


```
