### ISSUE TITLE
Screen Flickering on entering number in mobile

### ISSUE THREAD

**Issue by minkesh-pidilite** [ritikbanger/react18-input-otp#6]
- **Steps to reproduce the issue**:
Enter any OTP in browser in mweb

- **Relevant error messages and/or screenshots**:
Please see the video

https://user-images.githubusercontent.com/112943463/190124551-e17cd373-7a63-4a6b-aa83-2c47b7ec3c21.mp4

**Comment by ritikbanger** [comment]
Could you please share the code you have implemented, It seems that you are setting up a state triggering re-rendering of your view on every input.

I am unable to reproduce the same, please share more details or codesandbox.

**Comment by ritikbanger** [comment]
> This works fine on simulator but on actual mobile device this is causing an issue.

This indicates that there is no issue with the package, It maybe a system specific issue or any other programmatic error.

Two things to do here:

1. Try the same on another device.
2. Remove useEffect/counter code and then try.
